// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kit",
            "url": "https://github.com/kit-g"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exercises": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all exercises in a single page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "List all exercises",
                "operationId": "getExercises",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ExercisesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workouts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates, saves and returns a workout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Creates a workout",
                "operationId": "makeWorkout",
                "parameters": [
                    {
                        "description": "Workout request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkoutIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Workout"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "InternalError"
                },
                "error": {
                    "type": "string",
                    "example": "An unexpected error occurred"
                }
            }
        },
        "Exercise": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/ImageDescription"
                },
                "category": {
                    "type": "string",
                    "example": "Body weight"
                },
                "instructions": {
                    "type": "string",
                    "example": "Keep your body straight and lower yourself until your chest almost touches the ground."
                },
                "name": {
                    "type": "string",
                    "example": "Push Up"
                },
                "target": {
                    "type": "string",
                    "example": "Chest"
                },
                "thumbnail": {
                    "$ref": "#/definitions/ImageDescription"
                }
            }
        },
        "ExercisesResponse": {
            "type": "object",
            "properties": {
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Exercise"
                    }
                }
            }
        },
        "ImageDescription": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 100
                },
                "link": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "width": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "Set": {
            "type": "object",
            "required": [
                "completed",
                "id"
            ],
            "properties": {
                "completed": {
                    "type": "boolean",
                    "example": true
                },
                "distance": {
                    "type": "number",
                    "example": 10
                },
                "duration": {
                    "type": "number",
                    "example": 10
                },
                "id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "reps": {
                    "type": "integer",
                    "example": 10
                },
                "weight": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "Workout": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkoutExercise"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "2zsp6iMWgOx9n6qQxZm0GmeXog1"
                },
                "name": {
                    "type": "string",
                    "example": "Legs"
                },
                "start": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "WorkoutExercise": {
            "type": "object",
            "properties": {
                "exercise": {
                    "type": "string",
                    "example": "Push Up"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Set"
                    }
                }
            }
        },
        "WorkoutIn": {
            "type": "object",
            "required": [
                "exercises",
                "id",
                "start"
            ],
            "properties": {
                "end": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WorkoutExerciseIn"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "2zsp6iMWgOx9n6qQxZm0GmeXog1"
                },
                "name": {
                    "type": "string",
                    "example": "Legs"
                },
                "start": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "models.SetIn": {
            "type": "object",
            "required": [
                "completed"
            ],
            "properties": {
                "completed": {
                    "type": "boolean",
                    "example": true
                },
                "distance": {
                    "type": "number",
                    "example": 10
                },
                "duration": {
                    "type": "number",
                    "example": 10
                },
                "reps": {
                    "type": "integer",
                    "example": 10
                },
                "weight": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "models.WorkoutExerciseIn": {
            "type": "object",
            "required": [
                "exercise"
            ],
            "properties": {
                "exercise": {
                    "type": "string",
                    "example": "Push Up"
                },
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SetIn"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Heart of Yours API",
	Description:      "A simple fitness tracker API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
