// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kit",
            "url": "https://github.com/kit-g"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accounts are managed by Firebase so we just need to store them",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Creates an account record",
                "operationId": "registerAccount",
                "parameters": [
                    {
                        "description": "User request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Schedules account deletion for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Delete user account",
                "operationId": "deleteAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{accountId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns user account information for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get user account",
                "operationId": "getAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Performs various account editing actions: undoAccountDeletion, removeAvatar, uploadAvatar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Edit user account",
                "operationId": "editAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edit account request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EditAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PresignedUrlResponse"
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exercises": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all exercises in a single page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "List all exercises",
                "operationId": "getExercises",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ExercisesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/templates": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all workout templates for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Lists workout templates",
                "operationId": "getTemplates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Template"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates, saves and returns a workout template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Creates a workout template",
                "operationId": "makeTemplate",
                "parameters": [
                    {
                        "description": "Template request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TemplateIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Template"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/templates/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a specific workout template by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Get workout template",
                "operationId": "getTemplate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Template"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific workout template by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Delete workout template",
                "operationId": "deleteTemplate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workouts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated list of user workouts with exercises and sets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Returns user workouts",
                "operationId": "getWorkouts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size for pagination",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkoutResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates, saves and returns a workout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Creates a workout",
                "operationId": "makeWorkout",
                "parameters": [
                    {
                        "description": "Workout request",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkoutIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Workout"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workouts/{workoutId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single workout by ID with exercises and sets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Returns a workout",
                "operationId": "getWorkout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workout ID",
                        "name": "workoutId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Workout"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a workout by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Deletes a workout",
                "operationId": "deleteWorkout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workout ID",
                        "name": "workoutId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "EditAccountRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "example": "removeAvatar"
                },
                "mimeType": {
                    "type": "string",
                    "example": "image/png"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "InternalError"
                },
                "error": {
                    "type": "string",
                    "example": "An unexpected error occurred"
                }
            }
        },
        "Exercise": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/ImageDescription"
                },
                "category": {
                    "type": "string",
                    "example": "Body weight"
                },
                "instructions": {
                    "type": "string",
                    "example": "Keep your body straight and lower yourself until your chest almost touches the ground."
                },
                "name": {
                    "type": "string",
                    "example": "Push Up"
                },
                "target": {
                    "type": "string",
                    "example": "Chest"
                },
                "thumbnail": {
                    "$ref": "#/definitions/ImageDescription"
                }
            }
        },
        "ExercisesResponse": {
            "type": "object",
            "properties": {
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Exercise"
                    }
                }
            }
        },
        "ImageDescription": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 100
                },
                "link": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "width": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "PresignedUrlResponse": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "Set": {
            "type": "object",
            "required": [
                "completed",
                "id"
            ],
            "properties": {
                "completed": {
                    "type": "boolean",
                    "example": true
                },
                "distance": {
                    "type": "number",
                    "example": 10
                },
                "duration": {
                    "type": "number",
                    "example": 10
                },
                "id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "reps": {
                    "type": "integer",
                    "example": 10
                },
                "weight": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "SetIn": {
            "type": "object",
            "required": [
                "completed"
            ],
            "properties": {
                "completed": {
                    "type": "boolean",
                    "example": true
                },
                "distance": {
                    "type": "number",
                    "example": 10
                },
                "duration": {
                    "type": "number",
                    "example": 10
                },
                "reps": {
                    "type": "integer",
                    "example": 10
                },
                "weight": {
                    "type": "number",
                    "example": 100
                }
            }
        },
        "Template": {
            "type": "object",
            "properties": {
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TemplateExercise"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "2ztgx4cIWnxtt95klKnYGGtIfb1"
                },
                "name": {
                    "type": "string",
                    "example": "Legs \u0026 Shoulders"
                },
                "order": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "TemplateExercise": {
            "type": "object",
            "properties": {
                "exercise": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SetIn"
                    }
                }
            }
        },
        "TemplateIn": {
            "type": "object",
            "properties": {
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TemplateExercise"
                    }
                },
                "name": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                }
            }
        },
        "User": {
            "type": "object",
            "required": [
                "displayName",
                "email",
                "id"
            ],
            "properties": {
                "accountDeletionSchedule": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-07-12T12:11:54.450476-04:00"
                },
                "displayName": {
                    "type": "string",
                    "example": "jane_doe"
                },
                "email": {
                    "type": "string",
                    "example": "jane_doe@mail.com"
                },
                "id": {
                    "type": "string",
                    "example": "HW4beTVvbTUPRxun9MXZxwKPjmC2"
                },
                "scheduledForDeletionAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2025-07-15T12:11:54.450476-04:00"
                }
            }
        },
        "Workout": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkoutExercise"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "2zsp6iMWgOx9n6qQxZm0GmeXog1"
                },
                "name": {
                    "type": "string",
                    "example": "Legs"
                },
                "start": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "WorkoutExercise": {
            "type": "object",
            "properties": {
                "exercise": {
                    "type": "string",
                    "example": "Push Up"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Set"
                    }
                }
            }
        },
        "WorkoutExerciseIn": {
            "type": "object",
            "required": [
                "exercise"
            ],
            "properties": {
                "exercise": {
                    "type": "string",
                    "example": "Push Up"
                },
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SetIn"
                    }
                }
            }
        },
        "WorkoutIn": {
            "type": "object",
            "required": [
                "exercises",
                "id",
                "start"
            ],
            "properties": {
                "end": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/WorkoutExerciseIn"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "2zsp6iMWgOx9n6qQxZm0GmeXog1"
                },
                "name": {
                    "type": "string",
                    "example": "Legs"
                },
                "start": {
                    "type": "string",
                    "example": "2023-01-01T12:00:00Z"
                }
            }
        },
        "WorkoutResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Workout"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Heart of Yours API",
	Description:      "A simple fitness tracker API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
