// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kit",
            "url": "https://github.com/kit-g"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exercises": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all exercises in a single page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "List all exercises",
                "operationId": "getExercises",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ExercisesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "InternalError"
                },
                "error": {
                    "type": "string",
                    "example": "An unexpected error occurred"
                }
            }
        },
        "Exercise": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/ImageDescription"
                },
                "category": {
                    "type": "string",
                    "example": "Body weight"
                },
                "instructions": {
                    "type": "string",
                    "example": "Keep your body straight and lower yourself until your chest almost touches the ground."
                },
                "name": {
                    "type": "string",
                    "example": "Push Up"
                },
                "target": {
                    "type": "string",
                    "example": "Chest"
                },
                "thumbnail": {
                    "$ref": "#/definitions/ImageDescription"
                }
            }
        },
        "ExercisesResponse": {
            "type": "object",
            "properties": {
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Exercise"
                    }
                }
            }
        },
        "ImageDescription": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 100
                },
                "link": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "width": {
                    "type": "integer",
                    "example": 100
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Heart of Yours API",
	Description:      "A simple fitness tracker API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
