version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "heart-ci"
s3_bucket = "583168578067-sam"
s3_prefix = "heart-ci"
region = "ca-central-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = """
    Env=\"dev\"
"""
tags = """
    application=\"heart-ci\"
    AppManagerCFNStackKey=\"heart-ci\"
"""
