run:
  timeout: 4m
  tests: true           # lint *_test.go too
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck          # unchecked errors
    - govet             # vet passes
    - ineffassign       # assignments never used
    - staticcheck       # smart static analysis
    - unused            # dead code

    - gofmt
    - goimports

issues:
  # keep PR noise down: only show new issues vs main
  new: true

  # don’t fail the build on TODOs or generated files, etc.
  exclude-use-default: false
  exclude-rules:
    - path: ".*_generated\\.go"
      linters:
        - errcheck
        - staticcheck

skip-dirs:
  - vendor
  - .git
  - .github
