name: "Deploy"

on:
  push:
    branches: [ main, ci ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-artifact:
    name: "Build Lambda Artifact"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: api/go.sum

      - name: "Install dependencies"
        working-directory: api
        run: go mod download

      - name: "Build Lambda binary"
        working-directory: api
        run: ARTIFACTS_DIR=. make build-ApiFunction

      - name: "Zip Lambda binary"
        working-directory: api
        run: zip function.zip bootstrap

      - name: "Upload Lambda artifact"
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: api/function.zip

  api-tests:
    name: "Run API Tests"
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache: true
          cache-dependency-path: api/go.sum
      - name: "Run model tests"
        working-directory: "api/internal/models"
        run: go test . -v

  api-deploy:
    name: "Deploy Heart API"
    runs-on: ubuntu-latest
    needs: [ api-tests ]
    env:
      AWS_REGION: "ca-central-1"
      AWS_ROLE: "arn:aws:iam::583168578067:role/HeartGitHubActionsDeployRole"
      FUNCTION_NAME: "heart-api"
    steps:
#      - uses: actions/checkout@v3
#
#      - name: "Setup Go"
#        uses: actions/setup-go@v4
#        with:
#          go-version: '1.24'
#          cache: true
#          cache-dependency-path: api/go.sum

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Download Lambda Artifact"
        uses: actions/download-artifact@v4
        with:
          name: lambda-zip
          path: api/

      - name: "Update Api Lambda Function Code"
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://api/function.zip \
            --region ${{ env.AWS_REGION }} > /dev/null
