name: "Deploy"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  api-tests:
    name: "Run API Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: 'true'
          cache-dependency-path: "api/go.sum"
      - name: "Install dependencies"
        working-directory: api
        run: go mod download
      - name: "Run model tests"
        working-directory: "api/internal/models"
        run: go test . -v

  api-deploy:
    name: "Deploy Heart API"
    runs-on: ubuntu-latest
    needs: api-tests
    if: success()
    env:
      AWS_REGION: "ca-central-1"
      AWS_ROLE: "arn:aws:iam::583168578067:role/HeartGitHubActionsDeployRole"
      FUNCTION_NAME: "heart-api"
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: 'true'
          cache-dependency-path: "api/go.sum"

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Build Api Lambda Binary"
        run: ARTIFACTS_DIR=. make build-ApiFunction
        working-directory: api

      - name: "Zip Lambda Binary"
        run: zip function.zip bootstrap
        working-directory: api

      - name: "Update Api Lambda Function Code"
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://api/function.zip \
            --region ${{ env.AWS_REGION }} > /dev/null

